-- 1)
USE EMPRESA;

SELECT F.NOME, F.SALARIO
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D ON F.DNUMERO = D.DNUMERO
WHERE D.DNOME = "PESQUISA"
ORDER BY F.SALARIO ASC;

-- 2)

SELECT D.DNOME
FROM DEPARTAMENTO D
JOIN DEPTOLOCAL DL ON D.DNUMERO = DL.DNUMERO
WHERE DL.NOMELOCAL = 'São Paulo';


-- 3)

SELECT P.PROJNOME
FROM PROJETO P
JOIN DEPARTAMENTO D ON P.DNUMERO = D.DNUMERO
WHERE D.DNOME IN ('Pesquisa', 'Administração');

-- 4)

SELECT DISTINCT D.DNOME
FROM DEPARTAMENTO D
JOIN PROJETO P ON D.DNUMERO = P.DNUMERO
WHERE P.PROJLOCAL = 'São Paulo';

-- 5)

SELECT A.CPF, A.HORAS
FROM ATRIBUICAO A
JOIN PROJETO P ON A.PROJNUMERO = P.PROJNUMERO
WHERE P.PROJNOME = 'Novos benefícios'
ORDER BY A.HORAS DESC;

-- 6)

SELECT A.CPF, A.HORAS
FROM ATRIBUICAO A
JOIN PROJETO P ON A.PROJNUMERO = P.PROJNUMERO
WHERE P.PROJNOME LIKE '%Produto%'
ORDER BY A.HORAS DESC;

-- 7)

SELECT SUM(A.HORAS) AS TOTAL_HORAS
FROM ATRIBUICAO A
JOIN FUNCIONARIO F ON A.CPF = F.CPF
WHERE F.NOME = 'Fernando Wong';


-- 8)

SELECT COUNT(DISTINCT A.CPF) AS QTD_FUNCIONARIOS
FROM ATRIBUICAO A
JOIN PROJETO P ON A.PROJNUMERO = P.PROJNUMERO
WHERE P.PROJNOME = 'Produto Y';

-- 9)

SELECT P.PROJNOME, COUNT(DISTINCT A.CPF) AS QTD_FUNCIONARIOS
FROM ATRIBUICAO A
JOIN PROJETO P ON A.PROJNUMERO = P.PROJNUMERO
GROUP BY P.PROJNOME;

-- 10)

SELECT F.NOME, SUM(A.HORAS) AS TOTAL_HORAS
FROM ATRIBUICAO A
JOIN FUNCIONARIO F ON A.CPF = F.CPF
GROUP BY F.NOME;

-- 11)

SELECT F.NOME, F.SALARIO, A.HORAS
FROM ATRIBUICAO A
JOIN FUNCIONARIO F ON A.CPF = F.CPF
JOIN PROJETO P ON A.PROJNUMERO = P.PROJNUMERO
WHERE P.PROJNOME LIKE '%Produto%'
ORDER BY A.HORAS DESC;

-- 12)

SELECT P.PROJNOME
FROM PROJETO P
JOIN DEPARTAMENTO D ON P.DNUMERO = D.DNUMERO
JOIN DEPTOLOCAL DL ON D.DNUMERO = DL.DNUMERO
WHERE DL.NOMELOCAL = 'São Paulo';

-- 13)

SELECT AVG(F.SALARIO) AS MEDIA_SALARIO
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D ON F.DNUMERO = D.DNUMERO
JOIN DEPTOLOCAL DL ON D.DNUMERO = DL.DNUMERO
WHERE DL.NOMELOCAL = 'São Paulo';

-- 14)

SELECT DISTINCT P.PROJNOME
FROM PROJETO P
JOIN ATRIBUICAO A ON P.PROJNUMERO = A.PROJNUMERO
JOIN FUNCIONARIO F ON A.CPF = F.CPF
WHERE F.SEXO = 'F';

-- 15)

SELECT DISTINCT P.PROJNOME
FROM PROJETO P
JOIN DEPARTAMENTO D ON P.DNUMERO = D.DNUMERO
JOIN FUNCIONARIO F ON D.CPFGERENTE = F.CPF
WHERE F.SEXO = 'M';





